# -*- coding: utf-8 -*-
"""mining Simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mAXGqgyI0BflS3rPXRT9-4lLvOpVtCdp
"""

import hashlib
import time

class Block:
    def __init__(self, data):
        self.data = data
        self.nonce = 0
        self.hash = self.calculate_hash()

    def calculate_hash(self):
        value = self.data + str(self.nonce)
        return hashlib.sha256(value.encode()).hexdigest()

    def mine_block(self, difficulty):
        print(f"Starting mining with difficulty: {difficulty}")
        target = '0' * difficulty
        start_time = time.time()

        while self.hash[:difficulty] != target:
            self.nonce += 1
            self.hash = self.calculate_hash()

        end_time = time.time()
        print("Block mined successfully.")
        print(f"Hash: {self.hash}")
        print(f"Nonce attempts: {self.nonce}")
        print(f"Time taken: {end_time - start_time:.2f} seconds\n")

block = Block("Sample Block for Mining")
block.mine_block(4)